#####################################################
# This file is under control by chezmoi.
#####################################################

bind r source-file ~/.tmux.conf \; display "Reloaded!"

# キーストロークのディレイを減らす
set -sg escape-time 1

# スクロールバックを10000行に設定
set -g history-limit 10000

# vimのキーバインドでペインを移動する
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g default-terminal "screen-256color"

# ステータスバーの色を設定する
set -g status-bg "colour238"
set -g status-fg "colour255"

# 非アクティブpaneをグレーアウト
set -g window-style 'fg=colour247,bg=colour236'
set -g window-active-style 'fg=colour255,bg=terminal'

# 枠線の色
set -g pane-border-style 'fg=colour238'
set -g pane-active-border-style 'fg=colour51'

# タブの番号を1はじまりにする
set -g base-index 1

# コピーモード( ctrl-b+[ )時にvimっぽく動かす
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe 'xclip -in -selection clipboard'

# nvim OSC52 対応
set -g set-clipboard on

# ウィンドウやタブをショートカット経由で削除する場合に確認しない
bind-key & kill-window
bind-key x kill-pane

# paneを今いるパスで開く
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Resize the current pane using Alt + direction
bind-key -n M-Up resize-pane -U 5
bind-key -n M-Down resize-pane -D 5
bind-key -n M-Left resize-pane -L 5
bind-key -n M-Right resize-pane -R 5
